apiVersion: v2
name: oauth-server
description: > 
  A Helm chart for openFuyao OAuth2.0 server. It interacts with console-service to provide access token for each
  user. Users are required to input passwords for authentication.
type: application
version: 0.0.0-latest
appVersion: "latest"
keywords: ["openfuyao-component"]